Repository near/near-wallet, pull requests merged in 2021-02, with the labels that each got.

#1397 Update Chiense translations
  src/translations/zh-hans.global.json
  src/translations/zh-hant.global.json
Labels: 🌎 Translation

#1417 Add back fallback for missing translations
  src/components/Routing.js
Labels: 🐞 Bug

#1410 feat(fossa): added fossa integration
  .travis.yml
Labels: FOSSA, SRE
